const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { LoginGuard, LOCK_MS } = require('../login-guard');

test('third failure locks for a full hour, including correct codes and server restarts', t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bridge-guard-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  let now = 1000;
  const filename = path.join(dir, 'attempts.json');
  const guard = new LoginGuard(filename, () => now);
  const solve = (g, ip) => { const c = g.issue(ip); return g.check(ip, g.challenges.get(c.id).code, c.id); };
  assert.equal(guard.check('ip-a', 'invalid').status, 401);
  now += 10000;
  assert.equal(guard.check('ip-a', 'invalid').status, 401);
  now += 10000;
  assert.equal(guard.check('ip-a', 'invalid').retryAfter, 3600);
  assert.equal(solve(guard, 'ip-a').status, 429);
  assert.equal(solve(guard, 'ip-b').ok, true);
  const restarted = new LoginGuard(filename, () => now);
  now += LOCK_MS - 1;
  assert.equal(solve(restarted, 'ip-a').status, 429);
  now += 1;
  assert.equal(solve(restarted, 'ip-a').ok, true);
  assert.equal(restarted.check('ip-a', 'invalid').status, 401);
  assert.equal(solve(restarted, 'ip-a').ok, true);
  assert.equal(restarted.check('ip-a', 'invalid').error.includes('2 次'), true);
  const challenge = restarted.issue('ip-c');
  const code = restarted.challenges.get(challenge.id).code;
  assert.match(code, /^\d{4}$/);
  assert.equal(challenge.data.includes('<text'), false);
  assert.equal(restarted.check('ip-c', code, challenge.id).ok, true);
  assert.equal(restarted.check('ip-c', code, challenge.id).ok, false);
  const old = restarted.issue('ip-d');
  const oldCode = restarted.challenges.get(old.id).code;
  restarted.issue('ip-d', old.id);
  assert.equal(restarted.check('ip-d', oldCode, old.id).ok, false);
  const expired = restarted.issue('ip-e');
  const expiredCode = restarted.challenges.get(expired.id).code;
  now += 300001;
  assert.equal(restarted.check('ip-e', expiredCode, expired.id).ok, false);
});
